### ISSUE TITLE
Does not compile with Nginx 1.21.1

### ISSUE THREAD

**Issue by ip6li** [yaoweibin/nginx_ajp_module#51]
Compiler complains with:

```
nginx_ajp_module/ngx_http_ajp.c:140:29: Fehler: »ngx_http_request_t« {alias »struct ngx_http_request_s«} hat kein Element namens »space_in_uri«; meinten Sie »plus_in_uri«?
     if (r->quoted_uri || r->space_in_uri || r->internal) {
                             ^~~~~~~~~~~~
                             plus_in_uri
```

**Comment by FraPazGal** [comment]
Hello,

Is there any update on this? The compilation is failing with the following error:

```
ngx_http_ajp.c: In function 'sc_for_req_get_uri':
ngx_http_ajp.c:139:29: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'space_in_uri'; did you mean 'plus_in_uri'?
     if (r->quoted_uri || r->space_in_uri || r->internal) {
                             ^~~~~~~~~~~~
                             plus_in_uri
make[1]: *** [objs/Makefile:2251: objs/addon/nginx-module-ajp-0.20200326.0/ngx_http_ajp.o] Error 1
```

The error should be related to the changes performed in the latest NGINX version `1.21.1:

https://github.com/nginx/nginx/compare/release-1.21.0...release-1.21.1

**Comment by ip6li** [comment]
This one is outdated, see https://github.com/dvershinin/nginx_ajp_module

**Comment by ssticsistemas** [comment]
Hi,
same error and my solution with updated project:
in file ngx_http_ajp.c, line 139: _if (r->quoted_uri || r->**space_in_uri** || r->internal) {_
replace with: _if (r->quoted_uri || r->**plus_in_uri** || r->internal) {_
and rerun ./configure, make and make install
working correctly

**Comment by tao12345666333** [comment]
> Hi, same error and my solution with updated project: in file ngx_http_ajp.c, line 139: _if (r->quoted_uri || r->**space_in_uri** || r->internal) {_ replace with: _if (r->quoted_uri || r->**plus_in_uri** || r->internal) {_ and rerun ./configure, make and make install working correctly

In fact this behavior is inconsistent. You can just delete it.

```diff
- if (r->quoted_uri || r->space_in_uri || r->internal) {
+ if (r->quoted_uri || r->internal) {
```

`space_in_uri` is to handle some bad clients, but it's not necessary now

**Comment by yaoweibin** [comment]
Can you issue a pull request? Thanks.

Jintao Zhang ***@***.***> 于2022年10月26日周三 05:01写道：

**Comment by tao12345666333** [comment]
Sure!
